package com.runtimeterror.aild.db.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * @id is autogenerated by the Room
 * @title String, comes from the edit_text_title in the fragment CreateEntryFragment.kt
 * @date Long, timestamp of the journal, does not need to be created
 * @entryText This String is a filepath to the body of the journal entry, this does not hold the actual entry
 * @lucid This boolean value comes from the checkbox in CreateEntryFragment.kt
 */
@Entity(tableName = "journal")
data class Journal(
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0,
    var title: String = " ",
    var date: Long = System.currentTimeMillis(),
    var entryText: String = " ",
    var tags: List<String> = listOf(""),
    var lucid: Boolean = false,
)